### ISSUE TITLE
Would the ED4scan work with C453 4.6kW OBC?

### ISSUE THREAD

**Issue by zkertesz** [MyLab-odyssey/ED4scan#2]
Hi,

I drive a MY2018 C453 with a 4.6 kW (single phase, 20A) onboard charger, and, of course, interested in the monitoring of the charge process (at least). Your project is a perfect match for what I need.

In the wiki there's a note about this tool working only with the 22 kW and the 7.2 kW OBCs and wanted to know if it might work with the 4.6 kW as well or not.

As a side-note, I use the optional Mode 2 charging cable (domestic socket to type-2, build by Delphi), which limits the charging current to 10A and has NO current selection button or menu selector available (contrary to the manual), so the actual charging power is around 2kW (reported on the screen while changing).

Thanks a lot.
Zoli.

![img_7063](https://user-images.githubusercontent.com/10497781/42579738-a34e3f4c-8531-11e8-8601-6211770a1cd5.jpg)
![img_7062](https://user-images.githubusercontent.com/10497781/42579749-a83f27c8-8531-11e8-9e8e-a6a578dda2e1.jpg)

**Comment by MyLab-odyssey** [comment]
Hi Zoli,

the tool will work with your charger version. Actually there are only two charger options: a single phase 7.2kW isolated charger and a three phase non-isolated charger with 22kW. The 7.2kW version is limited by software to 20A, so that it will only use 4.6kW. The hardware is capable of charging with 7.2kW!

My software will report the charging parameters whatever build in charger is installed and whatever charging point is used. Your domestic charging cable is only simulation a charging point ;-)

There is a compiler option for the 22kW variant, but don't bother as you have the 4.6 (7.2) kW charger!

Just give ED4scan a try...

Best regards,
odyssey

**Comment by zkertesz** [comment]
Hi,

thanks a lot for the clarifications. Of course I'll give ED4scan a try. It's a really nice job you've done for the ED3 and 4. 

On the long run I'm looking for a way to monitor the charging (at least) remotely as it takes some time. 
The car is equipped with the GSM/3G telecommunication unit, but unfortunately the new Mercedes Me app is not available (yet?) for Romania and the old one doesn't accept new enrollments. That's why (and more importantly because it's a fun project) I'd like to build my own solution. 

Not sure yet on the final platform (Arduino, teensy or Rasberry Pi Zero) but most probably I'll send the data over a GPRS/3G modem to a MQTT broker. I'm leaning towards the Rpi 0 as I can have proper encryption which I've haven't seen implemented in the MQTT libraries written for Arduino or Teensy.

As I'd like to be permanently installed, I'm looking for a low-power platform which is active only when the car is plugged in. Still no clue how to detect that over the OBD port to switch on/off the device. As far as I know the 12V line is permanently on. 

But first thing first, I'll order a CAN shield to try out your tool :)

Regards,
Zoli.

**Comment by zkertesz** [comment]
Hi,

As far as I recall I've read that you have used a Raspberry Pi to do the initial reverse engineering on ED3.
As I had a can interface around (Dual Canberry with MCP2515) for Rpi tried it but with no real success.

It can see (receive) traffic on the interface but can't see any reply.

For example I've tried to get the ODO on ED4 with values taken from `_BMS_ED4_dfs.h`
`cansend can0 743#220207`

but can't see any reply with the ID  `0x763`.

Tried various modes to set up the interface, the results were the same.

Last attempt was:
`ip link set can0 up type can bitrate 500000 triple-sampling on listen-only off loopback off`

No matter how it's set up the interface showing an "ERROR-ACTIVE" state.

```
# ip -details -statistics link show can0
3: can0: <NOARP,UP,LOWER_UP,ECHO> mtu 16 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 10
    link/can  promiscuity 0
    can <TRIPLE-SAMPLING> state ERROR-ACTIVE restart-ms 0
	  bitrate 500000 sample-point 0.875
	  tq 125 prop-seg 6 phase-seg1 7 phase-seg2 2 sjw 1
	  mcp251x: tseg1 3..16 tseg2 2..8 sjw 1..4 brp 1..64 brp-inc 1
	  clock 8000000
	  re-started bus-errors arbit-lost error-warn error-pass bus-off
	  0          0          0          0          0          0         numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    RX: bytes  packets  errors  dropped overrun mcast
    11199499   1663295  1       0       1       0
    TX: bytes  packets  errors  dropped carrier collsns
    11         4        0       0       0       0
```

Any hints on what I'm doing wrong?

Thanks,
Zoli.
